# Generated by Django 6.0.5 on 2026-06-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpcode_attempts_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
